server:
  port: 80

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.223.121:3306/shangou_db?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://120.25.223.121/demo_db?serverTimezone=Asia/Shanghai

    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: i18n/validate
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #统一进行日期格式的数据返回
    time-zone: Asia/Shanghai   # 默认时区
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true

  mapper-locations: classpath*:mybatis/mapper/**/*.xml
---
logging:
  level:
    com.hl.shangou.dao: info
spring:
  profiles: pro
---
logging:
  level:
    com.hl.shangou.dao: trace
  profiles: dev

